#!/usr/bin/env python3
"""Generate static/syntax.css so code colours follow Duckquill's theme switcher.

Zola emits static/giallo-light.css and static/giallo-dark.css for class-based
highlighting, but Duckquill never links them (its head partial tests the
pre-0.22 config.markdown.highlight_code / highlight_theme keys, which no longer
exist). Even linking them directly is not enough: plain @import cannot be scoped
to a selector, so code would follow prefers-color-scheme while the rest of the
page follows the switcher's data-theme attribute.

This flattens both palettes into one stylesheet:

  * light rules unscoped, so they are the default
  * dark rules under :root[data-theme="dark"]      -> explicit dark
  * dark rules under :root:not([data-theme]) in a
    prefers-color-scheme: dark media query          -> switcher's "system"

Run after a build (Zola writes the inputs during `zola build`):

    zola build && python3 scripts/gen-syntax-css.py
"""

import pathlib
import re
import sys

STATIC = pathlib.Path(__file__).resolve().parent.parent / "static"
RULE = re.compile(r"([^{}]+)\{([^{}]*)\}", re.S)


def rules(path):
    """Yield (selector_list, declarations) pairs, comments discarded."""
    text = re.sub(r"/\*.*?\*/", "", path.read_text(), flags=re.S)
    for selectors, decls in RULE.findall(text):
        selectors = " ".join(selectors.split())
        decls = " ".join(decls.split())
        if selectors and decls:
            yield selectors, decls


def scope(selectors, prefix):
    """Prefix every comma-separated selector individually."""
    return ", ".join(f"{prefix} {s.strip()}" for s in selectors.split(","))


def emit(pairs, prefix=None, indent=""):
    out = []
    for selectors, decls in pairs:
        sel = scope(selectors, prefix) if prefix else selectors
        out.append(f"{indent}{sel} {{ {decls} }}")
    return "\n".join(out)


def main():
    light, dark = STATIC / "giallo-light.css", STATIC / "giallo-dark.css"
    missing = [p.name for p in (light, dark) if not p.exists()]
    if missing:
        sys.exit(f"missing {', '.join(missing)} — run `zola build` first")

    light_rules, dark_rules = list(rules(light)), list(rules(dark))

    css = f"""/*
 * GENERATED by scripts/gen-syntax-css.py — do not edit by hand.
 * Rebuild with: zola build && python3 scripts/gen-syntax-css.py
 *
 * Flattens Zola's giallo-light.css and giallo-dark.css into one stylesheet
 * scoped to Duckquill's data-theme attribute, so syntax colours follow the
 * nav theme switcher rather than only the OS colour scheme.
 */

/* Light is the default. */
{emit(light_rules)}

/* Explicit dark, chosen in the switcher. */
{emit(dark_rules, ':root[data-theme="dark"]')}

/* Switcher set to "system": no data-theme attribute, so defer to the OS. */
@media (prefers-color-scheme: dark) {{
{emit(dark_rules, ":root:not([data-theme])", indent="  ")}
}}
"""
    (STATIC / "syntax.css").write_text(css)
    print(f"wrote static/syntax.css ({len(light_rules)} light, {len(dark_rules)} dark rules)")


if __name__ == "__main__":
    main()
